/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.conexion;
import Modelo.modelo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Alejandro
 */
public class Menu_carreras extends javax.swing.JFrame {

    /**
     * Creates new form Menu_carreras
     */
    modelo km;
    public Menu_carreras() {
        initComponents();
        this.setTitle("Menu de circuito");
        
    }
    public void random (){
        
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFondo = new javax.swing.JLabel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_Circuito_km = new javax.swing.JTextField();
        random_km = new javax.swing.JCheckBox();
        jButton_Record_corredores = new javax.swing.JButton();
        jButton_iniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Nombre_corredor1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Nombre_corredor2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Nombre_corredor3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.jpg"))); // NOI18N

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltitulo.setText("Bienvenido al circuito");

        jLabel1.setText("Selecciona los corredores de hoy");

        jLabel3.setText("Selecciona el tamaño del circuito");

        random_km.setText("Kilometraje aleatorio");

        jButton_Record_corredores.setText("Consultar record de corredores");
        jButton_Record_corredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Record_corredoresActionPerformed(evt);
            }
        });

        jButton_iniciar.setText("Iniciar Carrera");
        jButton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciarActionPerformed(evt);
            }
        });

        jLabel4.setText("Primer piloto");

        Nombre_corredor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marc Marquez", "Jack Miller", "Alex Rins" }));
        Nombre_corredor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_corredor1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Segundo piloto");

        Nombre_corredor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Valentino Rossi", "Maverick Viñales", "Miguel Oliviera" }));

        jLabel6.setText("Tercer piloto");

        Nombre_corredor3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Danilo Petrucci", "Jorge Martin", "Luca Marini" }));

        jLabel2.setText("Entre 1 y 1000 kilometros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabeltitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton_Record_corredores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelFondo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17)
                                .addComponent(Nombre_corredor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre_corredor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_corredor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tx_Circuito_km, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_iniciar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(random_km)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabeltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre_corredor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_corredor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_corredor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tx_Circuito_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(random_km))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Record_corredores)
                            .addComponent(jButton_iniciar))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciarActionPerformed
       
       String nombre_corredor1 = Nombre_corredor1.getSelectedItem().toString();
       String nombre_corredor2 = Nombre_corredor2.getSelectedItem().toString();
       String nombre_corredor3 = Nombre_corredor3.getSelectedItem().toString();
       
       guardar(nombre_corredor1, nombre_corredor2,nombre_corredor3);
       
       if (random_km.isSelected()){
        int ran = (int)(Math.random()*1000+1);
        tx_Circuito_km.setEditable(false);
        tx_Circuito_km.setEnabled(false);
        km.setCircuito_km(ran);
       }else {
            int km_tx = Integer.parseInt(tx_Circuito_km.getText());
            km.setCircuito_km(km_tx);}
       
      
    }//GEN-LAST:event_jButton_iniciarActionPerformed

    conexion cn=new conexion();
    Connection con = cn.getConnection();
    PreparedStatement ps;   
    ResultSet rs;
    public void guardar(String nombre_corredor1, String nombre_corredor2, String nombre_corredor3){
    String sql = "insert into corredores_circuito (nombre_corredor1, nombre_corredor2, nombre_corredor3) values (?,?,?) ";

    try {
            
            con=cn.getConnection();
            ps=con.prepareStatement(sql); 
            ps.setString(1,(String) nombre_corredor1);
            ps.setString(2,(String) nombre_corredor2);
            ps.setString(3,(String) nombre_corredor3);
            ps.executeUpdate();
            ps.close();
            
        } catch (SQLException e) {
        }
       Carrera abrir = new Carrera();
       abrir.setVisible(true);
       this.setVisible(false);
    }
    private void Nombre_corredor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_corredor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_corredor1ActionPerformed

    private void jButton_Record_corredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Record_corredoresActionPerformed
        
            Consulta_corredores abrir = new Consulta_corredores();
            abrir.setVisible(true);
            this.setVisible(false);
       
    }//GEN-LAST:event_jButton_Record_corredoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_carreras().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox Nombre_corredor1;
    public static javax.swing.JComboBox Nombre_corredor2;
    public static javax.swing.JComboBox Nombre_corredor3;
    private javax.swing.JButton jButton_Record_corredores;
    private javax.swing.JButton jButton_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabeltitulo;
    public static javax.swing.JCheckBox random_km;
    public static javax.swing.JTextField tx_Circuito_km;
    // End of variables declaration//GEN-END:variables
}
