/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.conexion;
import Modelo.puestos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Alejandro
 */
public class Premiacion extends javax.swing.JFrame {
    private puestos corredor;
    conexion cn=new conexion();
    PreparedStatement ps;   
    ResultSet rs;
    Connection con = cn.getConnection();
    /**
     * Creates new form Premiacion
     */
     
    public void cargar(){
    String sql = "Select * from carrera";

    try {
            
            con=cn.getConnection();
            ps=con.prepareStatement(sql); 
            while (rs.next()){
                jTextField_primer_lugar.setText(""+rs.getString(1));
                jTextField_segundo_lugar.setText(""+rs.getString(2)); 
                jTextField_tercer_lugar.setText(""+rs.getString(3));
            }
            
        } catch (SQLException e) {
        }
       Carrera abrir = new Carrera();
       abrir.setVisible(true);
       this.setVisible(false);
    }
                
    public Premiacion() {
        initComponents();
        this.setTitle("Premiacion");
                jTextField_primer_lugar.setEditable(false);
                jTextField_segundo_lugar.setEditable(false);
                jTextField_tercer_lugar.setEditable(false);
                
                
                 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_primer_lugar = new javax.swing.JTextField();
        jTextField_tercer_lugar = new javax.swing.JTextField();
        jTextField_segundo_lugar = new javax.swing.JTextField();
        jButton_regresar_menu = new javax.swing.JButton();
        jLabel_1lugar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_primer_lugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_primer_lugar.setToolTipText("");
        jTextField_primer_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_primer_lugarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_primer_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, -1));

        jTextField_tercer_lugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_tercer_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tercer_lugarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_tercer_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, -1));

        jTextField_segundo_lugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_segundo_lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_segundo_lugarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_segundo_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        jButton_regresar_menu.setText("Finalizar");
        jButton_regresar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_regresar_menuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_regresar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel_1lugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/podio.jpg"))); // NOI18N
        getContentPane().add(jLabel_1lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 294));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_tercer_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tercer_lugarActionPerformed
        
    }//GEN-LAST:event_jTextField_tercer_lugarActionPerformed

    private void jTextField_segundo_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_segundo_lugarActionPerformed
        
    }//GEN-LAST:event_jTextField_segundo_lugarActionPerformed

    private void jTextField_primer_lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_primer_lugarActionPerformed
        
    }//GEN-LAST:event_jTextField_primer_lugarActionPerformed

    private void jButton_regresar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_regresar_menuActionPerformed
      
        
      Menu_carreras abrir = new Menu_carreras();
      abrir.setVisible(true);
      this.setVisible(false);
             
    }//GEN-LAST:event_jButton_regresar_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Premiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Premiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Premiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Premiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() { 
                
                new Premiacion().setVisible(true);
            } 
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_regresar_menu;
    private javax.swing.JLabel jLabel_1lugar;
    public javax.swing.JTextField jTextField_primer_lugar;
    public javax.swing.JTextField jTextField_segundo_lugar;
    public javax.swing.JTextField jTextField_tercer_lugar;
    // End of variables declaration//GEN-END:variables
}
